# Jekyll theme

theme: jekyll-theme-minimal

# General configuration

title: Panadestein's personal website
description: An overview of my research activities and scientific interests
show_downloads: "True"